console.log(
  '%c■■■■■■■■■■■■■%c\n%c🛑 ATTENTION 🛑%c\n%cIl s’agit d’une fonctionnalité de navigateur conçue pour les développeurs. Si quelqu’un vous a invité(e) à copier-coller quelque chose ici pour activer une fonctionnalité, sachez que c’est une escroquerie permettant à cette personne de potentiellement vous nuire.%c\n%c📣 INFO 📣%c\n%cVous pouvez retrouver le code source de ce projet sur github: %c\n%c🔗 https://github.com/mrstandu33/Portfolio 🔗%c\n%cVous pouvez aussi me retrouver en live sur Twitch: %c\n%c🔗 https://www.twitch.tv/mrstandu33 🔗',
  'color: rgba(0, 0, 0, 0); margin-top: 5px; background-image: url(https://daniels-roth-stan.fr/ressources/svg/logo.svg); background-size: contain; line-height: 156px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; margin-top: 20px; font-size: 24px; color: #F7FBFC; background-color: #F26060; border-radius: 3px; padding: 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; margin-top: 5px; font-size: 14px; color: #F7FBFC; background-color: #73739e; border-radius: 3px; padding: 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; margin-top: 20px; font-size: 24px; color: #000000; background-color: #FFC107; border-radius: 3px; padding: 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; margin-top: 5px; font-size: 14px; padding: 5px 5px 0 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; font-size: 14px; padding: 0 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; font-size: 14px; padding: 0 5px;',
  'background-color: rgba(0, 0, 0, 0);',
  'font-family: Helvetica; font-size: 14px; padding: 0 5px',
);
